---
deployment:
  tasks:
    - export REPOPATH=/home/timetowe/repositories/test/*
    - export SITEPATH=/home/timetowe/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH